process.on('uncaughtException', function ( err ) {
 
  throw err;
});

throw "on purpose"
